2022-04-12 11:43:03,570 ERROR: Exception on /index [GET] [in /home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/index.html", line 11, in block 'app_content'
    {% include '_post.html' %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/_post.html", line 21, in template
    <a href="javascript:translate('#post{{ post.id }}', '#translation{{ post.id }}', '{{ post.language }}', '{{ g.locale }}');">{{ console.log(translate("#post{{ post.id }}", "#translation{{ post.id }}", "{{ post.language }}", "{{ g.locale }}");), _('Translate') }}</a>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got ';'
2022-04-12 11:44:59,776 INFO: Microblog startup [in /home/jansen/Documentos/projetos/flask/microblog/app/__init__.py:52]
2022-04-12 11:45:01,839 ERROR: Exception on /index [GET] [in /home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/base.html", line 11, in block 'navbar'
    <h1>{{ console.log(verificar) }}</h1>
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'console' is undefined
2022-04-12 11:45:40,738 INFO: Microblog startup [in /home/jansen/Documentos/projetos/flask/microblog/app/__init__.py:52]
2022-04-12 11:45:49,557 ERROR: Exception on /index [GET] [in /home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jansen/Documentos/projetos/flask/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jansen/Documentos/projetos/flask/microblog/app/templates/base.html", line 11, in template
    <h1>{{ javascript: console.log(verificar) }}</h1>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
